---
# tasks file for httpd
- name: Check if EPEL repo is already configured.
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
### installing dependencies
- name: installing all the dependent packages
  yum: 
    name: '{{ item }}' 
    state: present
  with_items: '{{ package_list }}'
  become: yes

# creating other directories
- name: creating directories inside build
  file: 
      path: /usr/build/{{ item }}
      state: directory
      mode: 0755
  with_items:
       - 'apr'
       - 'apr_util'
       - 'apache'

#extracting to build directories
- name: extracting apr, apr utils, httpd to build directory
  unarchive: 
       src: '{{ item.url }}'
       dest: '{{ dest_build }}/{{ item.dir }}'
       remote_src: no
       owner: '{{ user }}'
       group: '{{ group }}'
  with_items: 
       - { url: '{{ apr }}',      dir: 'apr'}
       - { url: '{{ apr_util }}', dir: 'apr_util'}
       - { url: '{{ httpd }}',    dir: 'apache'}
  become: yes

######################## Installing APR
#configuring apr
- name: configuring apr
  command: ./configure --prefix=/usr/local/apr-httpd/
  args:
   chdir: '{{ dest_build }}/apr/{{ apr_version }}'
  become: yes

#compiling apr
- name: compiling apr
  command: make
  args:
   chdir: '{{ dest_build }}/apr/{{ apr_version }}'
  become: yes

## installing apr
- name: installing apr
  command: make install
  args:
   chdir: '{{ dest_build }}/apr/{{ apr_version }}'
  become: yes
  
  ###################### Installing APR-Utils
  #configuring apr-util
- name: configuring apr-util
  command: ./configure --with-apr=/usr/local/apr-httpd/ --prefix=/usr/local/apr-util-httpd/
  args:
   chdir: '{{ dest_build }}/apr_util/{{ apr_util_version }}'
  become: yes

#compiling apr-util
- name: compiling apr-util
  command: make
  args:
   chdir: '{{ dest_build }}/apr_util/{{ apr_util_version }}'
  become: yes

## installing apr-util
- name: installing apr-util
  command: make install
  args:
   chdir: '{{ dest_build }}/apr_util/{{ apr_util_version }}'
  become: yes

########################### Installing Httpd
#configuring httpd
- name: configuring httpd
  command: ./configure --with-apr=/usr/local/apr-httpd/ --with-apr-util=/usr/local/apr-util-httpd/ --with-ssl --enable-proxy=shared --enable-ssl --enable-mods-shared=all --enable-so CC=gcc
  args:
   chdir: '{{ dest_build }}/apache/{{ httpd_version }}'
  become: yes

#compiling httpd
- name: compiling httpd
  command: make
  args:
   chdir: '{{ dest_build }}/apache/{{ httpd_version }}'
  become: yes

## installing httpd
- name: installing httpd
  command: make install
  args:
   chdir: '{{ dest_build }}/apache/{{ httpd_version }}'
  become: yes
